CREATE TABLE review_replies (
  id SERIAL PRIMARY KEY,
  review_id INTEGER UNIQUE REFERENCES reviews(id) ON DELETE CASCADE NOT NULL,
  owner_id INTEGER REFERENCES owners(id) ON DELETE CASCADE NOT NULL,
  body TEXT NOT NULL,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE reviews
ADD COLUMN seen BOOLEAN DEFAULT false;
