ALTER TABLE users
ADD COLUMN name VARCHAR(50),
ADD COLUMN createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW();

UPDATE users
SET name = ('User #' || id);

ALTER TABLE users
ALTER COLUMN name SET NOT NULL;